### ISSUE TITLE
feature request: shift pixels in image

### ISSUE THREAD

**Issue by cdaringe** [jvalen/pixel-art-react#13]
# problem

i need to bulk move all my pixels, otherwise shrinking the image truncates my art!

**Comment by jvalen** [comment]
Hi @cdaringe!

Thanks for your feedback. Yes, I'm aware of that issue, right now I'm working on code some refactoring, I'll take your request into consideration for next features.

**Comment by jvalen** [comment]
Hi @cdaringe,

Sorry it took so long to have this feature in the app, now is ready and working in production.
You can shift pixels around with what I called the "Move" tool in both desktop and mobile.

Thank you!
