### ISSUE TITLE
feature request: export my art in format that can be imported back into the app

### ISSUE THREAD

**Issue by cdaringe** [jvalen/pixel-art-react#14]
title says it all!

**Comment by jvalen** [comment]
Hi @cdaringe!

If I understood correctly, the feature that you are requesting is already implemented, maybe not very intuitive to do though.

You could do your art, then click on the LOAD button, go to EXPORT tab and copy the generated code somewhere you want to keep it (plain text). If you want to restore that project, you'd just need to go to LOAD button, IMPORT tab, paste the code and press IMPORT button.

Please, let me know if I misunderstood your request.
Thanks!

**Comment by cdaringe** [comment]
oh, nice! i ended up dumping localStorage, but looks like you already did it!  thanks!
