### ISSUE TITLE
Drawing in black although first cell of palette is other color

### ISSUE THREAD

**Issue by xgbuils** [jvalen/pixel-art-react#25]
Steps to reproduce:
- Select the color picker.
- Change the color of first cell (for example, pick a `#5599dd` color)
- Save the project
- reload the page (palette has the color `#5599dd` in first cell)
- Draw a cell

Expected behaviour:
Cell is drawn with color `#5599dd`
Current behaviour:
Cell is drawn with color `#000000`

### Possible solution:
Now we have:
- a `paletteGridData` prop as a List of objects {color, id} 
- a `currentColor` prop as an object {color, position}

I think there are redundant data that causes this kind of bugs when data is not well syncronized. I propose refactor the state to a List of colors and a cell active position. I think that in this case could be enough to represent the state of palette.

I'm working in converting the main reducer in a composition of subreducers that handles the different substates of aplication (palette, drawing tool, active grid, frames, etc) simplifying the relation between state and actions and allowing easier unit tests.

These are the branches where I'm working sequantially after #22 PR:
- [Implement drawing tool reducer](https://github.com/jvalen/pixel-art-react/pull/26)
- [Implement palette reducer](https://github.com/jvalen/pixel-art-react/pull/27)

I could fix this issue after implementing palette reducer. I could be easier to fix.

Cheers!

**Comment by jvalen** [comment]
Nice catch! It sounds good, let me review the PR so you can resume the reducers refactor.
Thank you!
