### ISSUE TITLE
Import doesn't work

### ISSUE THREAD

**Issue by raspacorp** [jvalen/pixel-art-react#35]
When I try to import previously exported code it shows the error message: "Sorry, the project couldn't be imported"

I am exporting a single image CSS, then trying to load it with the load button and pasting the css code there.

**Comment by jvalen** [comment]
Hi @raspacorp,

Thank you for raising the issue, unfortunately I haven't been able to reproduce the problem. I've tried creating a single image as well as a sequence of them having not problem at all.

Could you provide more information? Is this export from long time ago? browser? even better if you are willing to share the image exported data will be probably easier to find to problem.

Thanks
