### ISSUE TITLE
Node v16 LTS is coming soon; any plans to lock in v12 LTS for compatibility?

### ISSUE THREAD

**Issue by bedwardly-down** [jvalen/pixel-art-react#47]
According to [this](https://terasoltechnologies.com/node-16-latest-upgrades-and-features-2021/), V16 will go LTS on October 26. When that happens, several packages used will probably break for anyone that uses your project. Currently, I was able to get it to work fine with v14 but I haven't tested with v16 yet. I also would be willing to open a PR and do the work to help with that.

**Comment by jvalen** [comment]
Hi @bedwardly-down,

Thank you for presenting your initiative, feel free to create a PR for v14, not for v16 yet though.
I might add some changes in the near future in the server side, so I'd rather not to change much.

Thanks again!

**Comment by bedwardly-down** [comment]
Can do. Any issue with me adding Nodejs v14 as a devDependency and enforcing engine strictness so that when v16 drops and systems like Gentoo or Arch force an upgrade to it, users should still be able to run without issue?

**Comment by jvalen** [comment]
Sure, just please remove the package-lock from the PR as I mention in the comment.
Thank you.
