### ISSUE TITLE
Gifs transparency

### ISSUE THREAD

**Issue by blipn** [jvalen/pixel-art-react#51]
Hello, maybe you can enable gif transparence
i tried to modify src\utils\canvasGIF.js with `gif.setTransparent(0x00ff00);` and setDispose to the default value `gif.setDispose(2)`
but is seems not to be the best thing to do because you will have to change the first default palette color and 'rgba(0, 0, 0, 1)' that will always be a transparent color.

Thank you & have a good day ;)

**Comment by arbutt1010** [comment]
How can I configure this project to my local machine, I had done all prerequisites but still I am unable to get results
**NodeJS Version: v14.0.0**
**NPM Version: v7.0.0**
When I do `npm run development`
It gives output 
but when I run `npm run server`
I get this error
```
PS C:\Users\Fakhar Anwar\Desktop\Project\pixel-art-nfts> npm run server

> pixel-art-react@3.10.0 server
> node ./src/server/loader

Version deployed: 3.10.0
internal/fs/utils.js:259
    throw err;
    ^

Error: ENOENT: no such file or directory, open 'config.json'
    at Object.openSync (fs.js:461:3)
    at Object.readFileSync (fs.js:364:35)
    at Object.<anonymous> (C:\Users\Fakhar Anwar\Desktop\Project\pixel-art-nfts\src\server\/server.js:34:30)
    at Module._compile (internal/modules/cjs/loader.js:1185:30)
    at Module._compile (C:\Users\Fakhar Anwar\Desktop\Project\pixel-art-nfts\node_modules\pirates\lib\index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:1205:10)
    at Object.newLoader [as .js] (C:\Users\Fakhar Anwar\Desktop\Project\pixel-art-nfts\node_modules\pirates\lib\index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:1034:32)
    at Function.Module._load (internal/modules/cjs/loader.js:923:14)
    at Module.require (internal/modules/cjs/loader.js:1074:19) {
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: 'config.json'
}
```
Initially when i run `npm install`
A pop-up came in notes with **webpack.production.config.js** 
I add that pop-up code as **config.js** in **root**  still got same error
I added that pop-up file as **config.json** in **root** still got same error
If any help me to configure this project please

**Comment by blipn** [comment]
maybe you user name "Fakhar Anwar" is breaking some links, space character is not always welcome

**Comment by jvalen** [comment]
Hi @arbutt1010,

I believe that the problem you are having is due to the `config.json` file does not contain the proper constants defined. I just added an example in the README.md:

```
{
  "dev": {
    "EXPRESS_SESSION_SECRET": "1234"
  }
}
```

I hope it helps

**Comment by jvalen** [comment]
Hi @blipn,

Sorry for the delayed response and thanks for the request.

The method you mentioned requires to set a color as the transparent one, meaning that if someone uses it in their drawing, it will be showed as transparent. I.e. If someone uses 0x00ff00 (a green color tone) they might found unexpected behavior in their GIF animation. It would be great to do something like: `gif.setTransparent(0x00000000);` adding the 2 latest hex digits as alpha value but it does not seem to work.

At the moment the library does no support transparency for that purposes without sacrificing a color for transparency, which I'm not a big fan of.

Thank you anyway
