### ISSUE TITLE
Eraser Tool

### ISSUE THREAD

**Issue by lab596** [jvalen/pixel-art-react#52]
Hello! I'm brand new to this project and I was having fun playing around with the interface. One enhancement that I found could be added is a symbol that follows the cursor when using the eraser tool similar to the "plus sign" that comes up when you are on the paint tool. I would like to add something like this but as I said I am brand new to this project. If someone could tell me where to start that would be much appreciated.

**Comment by jvalen** [comment]
Hi @lab596,

The way it is implemented is just using the [`cursor`](https://developer.mozilla.org/en-US/docs/Web/CSS/cursor) css property, this way the images rendered while hovering a cell are the native cursors of the browser.

You can see [here](https://github.com/jvalen/pixel-art-react/blob/master/src/css/components/_PixelGrid.css#L20) that the one used for the eraser tool is the `context-menu` which is not very accurate for its purpose I agree. We could set a custom image using `cursor: url("image-url"), auto;` but I'm not considering changing this part at the moment, maybe in the future if I decide to do a style revamp.

Thank you!
