### ISSUE TITLE
Thanks for creating this tool

### ISSUE THREAD

**Issue by DrDru** [jvalen/pixel-art-react#56]
Hi

I just wanted to say thank you for creating this tool. Someone has kindly made a tool that allows me to combine the css outputs I get from your tool (here https://www.thecodingfox.com/interactive/pixel-world-editor/  ).

That has allowed me to create a sort of pixel art illustrated comic book  ( here : https://drdru.github.io/stories/twc_save_aryn/02_on_the_way_to_kilm_1.html )

My workflow is as follow :

- download free video game tiles / sprites

- turns them  to CSS using pixelartccs

- make illustration using pixel-world-editor

- add the HTML/CSS output into a custom template.

Cheers

**Comment by jvalen** [comment]
That's great! Thanks for sharing the project and your kind words.
People enjoying the tool and being creative with it is probably the main reason why I keep maintaining my project :relaxed:

Thanks again!
